In [13]:
# 数据的导入
import pandas as pd
df = pd.read_csv('C:/Users/Lenovo/Desktop/python数据分析/employees.csv')
print(type(df))
display(df.tail())
print(df.SALARY.mean())
#数据的导出
df= df.tail()
df.to_csv('C:/Users/Lenovo/Desktop/python数据分析/new_employees.csv')

<class 'pandas.DataFrame'>

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
595,695,Joyce,Vance,JVANCE,515.163.6253,AC_ACCOUNT,7354.0,NaN,122.0,110
596,696,Howard,Walker,HWALKER,515.127.7657,AC_ACCOUNT,8289.0,NaN,122.0,110
597,697,Julia,Spencer,JSPENCER,515.145.2246,AC_ACCOUNT,8086.0,NaN,122.0,110
598,698,Angela,Long,ALONG,515.190.1561,AC_ACCOUNT,7060.0,NaN,122.0,110
599,699,Frances,Martin,FMARTIN,515.160.5926,AC_ACCOUNT,7914.0,NaN,122.0,110

6634.663333333333

In [35]:
import json

with open('C:/Users/Lenovo/Desktop/python数据分析/data1.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

print(data)
print(type(data))
df = pd.DataFrame(data)
display(df)
print(type(df))

{'张三': {'性别': '男', '年龄': 28, '邮箱': 'zhangsan@example.com'}, '李四': {'性别': '女', '年龄': 25, '邮箱': 'lisi@example.com'}, '王五': {'性别': '男', '年龄': 32, '邮箱': 'wangwu@example.com'}}
<class 'dict'>

                      张三                李四                  王五
性别                     男                 女                   男
年龄                    28                25                  32
邮箱  zhangsan@example.com  lisi@example.com  wangwu@example.com

<class 'pandas.DataFrame'>

In [64]:
# 缺失值的处理
import pandas as pd
import numpy as np
s = pd.Series([12,25,np.nan, None, pd.NA])
df = pd.DataFrame([[12,pd.NA,2],[25,3,5],[None,4,6]],
                  columns=['第一列','第二列','第三列'])
print(s)
# 缺失值的检测
print(s.isna())
print(s.isnull())
print(df.isna())
print(df.isnull())
print(df.isna().sum(axis=1)) #列
print(s.isna().sum())
print('-'*30)
# 剔除缺失值
print(s.dropna())
print(df.dropna())
print(df.dropna(how='all')) 
print(df.dropna(thresh=2))# 至少两个不是缺失值就保留
print(df.dropna(axis=1))# 剔除一整列的记录
print(df.dropna(subset=['第一列']))

0      12
1      25
2     NaN
3    None
4    <NA>
dtype: object
0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
0    1
1    0
2    1
dtype: int64
3
------------------------------
0    12
1    25
dtype: object
    第一列 第二列  第三列
1  25.0   3    5
    第一列   第二列  第三列
0  12.0  <NA>    2
1  25.0     3    5
2   NaN     4    6
    第一列   第二列  第三列
0  12.0  <NA>    2
1  25.0     3    5
2   NaN     4    6
   第三列
0    2
1    5
2    6
    第一列   第二列  第三列
0  12.0  <NA>    2
1  25.0     3    5

In [71]:
# 缺失值填充
df = pd.read_csv('C:/Users/Lenovo/Desktop/python数据分析/employees.csv')
df.tail()
df.isna().sum(axis=0)

EMPLOYEE_ID         0
FIRST_NAME         14
LAST_NAME           5
EMAIL              32
PHONE_NUMBER       31
JOB_ID              8
SALARY             29
COMMISSION_PCT    453
MANAGER_ID         19
DEPARTMENT_ID      10
dtype: int64