In [1]:
# 数据的导入
import pandas as pd
df = pd.read_csv('C:/Users/Lenovo/Desktop/python数据分析/employees.csv')
print(type(df))
display(df.tail())
print(df.SALARY.mean())
#数据的导出
df= df.tail()
df.to_csv('C:/Users/Lenovo/Desktop/python数据分析/new_employees.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Lenovo/Desktop/python数据分析/employees.csv'

In [ ]:
import json

with open('C:/Users/Lenovo/Desktop/python数据分析/data1.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

print(data)
print(type(data))
df = pd.DataFrame(data)
display(df)
print(type(df))

{'张三': {'性别': '男', '年龄': 28, '邮箱': 'zhangsan@example.com'}, '李四': {'性别': '女', '年龄': 25, '邮箱': 'lisi@example.com'}, '王五': {'性别': '男', '年龄': 32, '邮箱': 'wangwu@example.com'}}
<class 'dict'>

                      张三                李四                  王五
性别                     男                 女                   男
年龄                    28                25                  32
邮箱  zhangsan@example.com  lisi@example.com  wangwu@example.com

<class 'pandas.DataFrame'>

In [ ]:
# 缺失值的处理
import pandas as pd
import numpy as np
s = pd.Series([12,25,np.nan, None, pd.NA])
df = pd.DataFrame([[12,pd.NA,2],[25,3,5],[None,4,6]],
                  columns=['第一列','第二列','第三列'])
print(s)
# 缺失值的检测
print(s.isna())
print(s.isnull())
print(df.isna())
print(df.isnull())
print(df.isna().sum(axis=1)) #列
print(s.isna().sum())
print('-'*30)
# 剔除缺失值
print(s.dropna())
print(df.dropna())
print(df.dropna(how='all')) 
print(df.dropna(thresh=2))# 至少两个不是缺失值就保留
print(df.dropna(axis=1))# 剔除一整列的记录
print(df.dropna(subset=['第一列']))

0      12
1      25
2     NaN
3    None
4    <NA>
dtype: object
0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
0    1
1    0
2    1
dtype: int64
3
------------------------------
0    12
1    25
dtype: object
    第一列 第二列  第三列
1  25.0   3    5
    第一列   第二列  第三列
0  12.0  <NA>    2
1  25.0     3    5
2   NaN     4    6
    第一列   第二列  第三列
0  12.0  <NA>    2
1  25.0     3    5
2   NaN     4    6
   第三列
0    2
1    5
2    6
    第一列   第二列  第三列
0  12.0  <NA>    2
1  25.0     3    5

In [ ]:
# 缺失值填充
df = pd.read_csv(r'C:\Users\Lenovo\Desktop\Python_Data _analysis\employees.csv')
df.tail()
df.isna().sum(axis=0)

EMPLOYEE_ID         0
FIRST_NAME         14
LAST_NAME           5
EMAIL              32
PHONE_NUMBER       31
JOB_ID              8
SALARY             29
COMMISSION_PCT    453
MANAGER_ID         19
DEPARTMENT_ID      10
dtype: int64

In [ ]:
# 时间数据的处理
import pandas as pd
d = pd.Timestamp('2025-02-28 10:22')
d1 = pd.Timestamp('2025-02-28 13:22')
print(d)
print(type(d))
print("月：",d.month)
print("日：",d.day)
print("季度：",d.quarter)
print("是否是月底：",d.is_month_end)
print("星期几：",d.day_name())
print("转换为季度：",d.to_period("Q"))
print("转换为月度：",d1.to_period("M"))

2025-02-28 10:22:00
<class 'pandas.Timestamp'>
月： 2
日： 28
季度： 1
是否是月底： True
星期几： Friday
转换为季度： 2025Q1
转换为月度： 2025-02

In [ ]:
# 字符串转换为日期类型
a = pd.to_datetime('20150228')
print(a)
print(type(a))
print(a.day_name())
# dataframe 日期转换
df = pd.DataFrame({
    'sales':[100,200,300],
    'date':['20250601','20250602','20250603']
})
df['datetime'] = pd.to_datetime(df['date'])
df
print(df.info())
print(type(df['datetime']))
df['week'] = df['datetime'].dt.day_name()
df['datetime'].dt.year

2015-02-28 00:00:00
<class 'pandas.Timestamp'>
Saturday
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sales     3 non-null      int64
 1   date      3 non-null      str
 2   datetime  3 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 204.0 bytes
None
<class 'pandas.Series'>

0    2025
1    2025
2    2025
Name: datetime, dtype: int32

In [ ]:
# csv 日期转换
df = pd.read_csv(r'C:\Users\Lenovo\Desktop\Python_Data _analysis\weather.csv',parse_dates=['date'])
#df['datetime'] = pd.to_datetime(df['date'])
#display(df['datetime'].dt.day_name())
df.info()
df['date'].dt.day_name()

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[us]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 68.6 KB

0          Sunday
1          Monday
2         Tuesday
3       Wednesday
4        Thursday
          ...
1456       Sunday
1457       Monday
1458      Tuesday
1459    Wednesday
1460     Thursday
Name: date, Length: 1461, dtype: str

In [ ]:
# 日期数据作为索引
#df.set_index('date' , inplace=True) # 将原来的索引直接在源文件中生效
print(df.loc["2013-01":"2013-02"])

            precipitation  temp_max  temp_min  wind  weather
date
2013-01-01            0.0       5.0      -2.8   2.7      sun
2013-01-02            0.0       6.1      -1.1   3.2      sun
2013-01-03            4.1       6.7      -1.7   3.0     rain
2013-01-04            2.5      10.0       2.2   2.8     rain
2013-01-05            3.0       6.7       4.4   3.1     rain
2013-01-06            2.0       7.2       2.8   3.0     rain
2013-01-07            2.3      10.0       4.4   7.3     rain
2013-01-08           16.3      11.7       5.6   6.3     rain
2013-01-09           38.4      10.0       1.7   5.1     rain
2013-01-10            0.3       3.3      -0.6   2.1     snow
2013-01-11            0.0       2.8      -2.8   1.9  drizzle
2013-01-12            0.0       2.8      -3.9   2.0      sun
2013-01-13            0.0       2.2      -4.4   1.5      sun
2013-01-14            0.0       3.3      -2.2   1.3      sun
2013-01-15            0.0       6.7      -0.6   2.3      sun
2013-01-16            0.0       6.1      -3.9   1.8  drizzle
2013-01-17            0.0       3.9      -2.8   1.0  drizzle
2013-01-18            0.0       3.3      -1.1   1.3  drizzle
2013-01-19            0.0       1.1      -0.6   1.9  drizzle
2013-01-20            0.0       3.3      -0.6   2.1  drizzle
2013-01-21            0.0       2.2      -1.7   1.1  drizzle
2013-01-22            0.0       3.3      -1.7   0.6  drizzle
2013-01-23            5.1       7.2       2.2   3.1     rain
2013-01-24            5.8       7.2       1.1   2.6     rain
2013-01-25            3.0      10.6       2.8   2.1     rain
2013-01-26            2.3       8.3       3.9   4.5     rain
2013-01-27            1.8       5.6       3.9   4.5     rain
2013-01-28            7.9       6.1       3.3   3.2     rain
2013-01-29            4.3       8.3       5.0   3.9     rain
2013-01-30            3.6       8.9       6.7   3.9     rain
2013-01-31            3.0       9.4       7.2   4.0     rain
2013-02-01            0.3      11.7       5.0   2.9     rain
2013-02-02            0.0       6.1       2.8   2.0  drizzle
2013-02-03            2.3       8.9       2.8   2.9     rain
2013-02-04            0.0      10.6       6.7   2.6     rain
2013-02-05            3.3      10.0       6.7   5.1     rain
2013-02-06            1.0      10.6       6.1   4.5     rain
2013-02-07            1.3       9.4       3.3   4.1     rain
2013-02-08            0.0       7.8       2.2   1.3      sun
2013-02-09            0.3       8.3       4.4   1.3     rain
2013-02-10            0.0       8.9       1.7   2.0  drizzle
2013-02-11            0.3       8.3       4.4   1.4     rain
2013-02-12            1.0      11.1       7.2   5.6     rain
2013-02-13            2.3       9.4       7.2   4.1     rain
2013-02-14            1.0       9.4       5.6   2.2     rain
2013-02-15            0.0      13.3       5.0   2.4  drizzle
2013-02-16            0.0      11.1       3.9   5.6     rain
2013-02-17            0.0       9.4       4.4   3.4     rain
2013-02-18            0.0       7.8       3.9   1.9     rain
2013-02-19            0.0      10.6       1.7   3.4      sun
2013-02-20            1.5       7.8       1.1   2.1     rain
2013-02-21            0.5       6.7       3.9   6.2     rain
2013-02-22            9.4       7.8       3.9   8.1     rain
2013-02-23            0.3      10.0       3.9   4.6     rain
2013-02-24            0.0       8.9       5.0   5.5     rain
2013-02-25            2.3      10.6       3.3   7.1     rain
2013-02-26            0.5       8.9       3.9   3.8     rain
2013-02-27            4.6      10.0       4.4   1.8     rain
2013-02-28            8.1      11.7       6.7   3.8     rain

In [ ]:
# 计算时间间隔
d1 = pd.Timestamp('2013-01-15')
d2 = pd.Timestamp('2023-02-23')
d3 = d2 - d1
print(d3)
print(type(d3))

3691 days 00:00:00
<class 'pandas.Timedelta'>

In [ ]:
df = pd.read_csv(r'C:\Users\Lenovo\Desktop\Python_Data _analysis\weather.csv',parse_dates=['date'])
df.info()
df['delta'] = df['date'] - df['date'][0]
df.set_index('delta',inplace=True)

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[us]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 68.6 KB

In [ ]:
df
print(df.loc['10 days':'20 days'])

              date  precipitation  temp_max  temp_min  wind weather
delta
10 days 2012-01-11            0.0       6.1      -1.1   5.1     sun
11 days 2012-01-12            0.0       6.1      -1.7   1.9     sun
12 days 2012-01-13            0.0       5.0      -2.8   1.3     sun
13 days 2012-01-14            4.1       4.4       0.6   5.3    snow
14 days 2012-01-15            5.3       1.1      -3.3   3.2    snow
15 days 2012-01-16            2.5       1.7      -2.8   5.0    snow
16 days 2012-01-17            8.1       3.3       0.0   5.6    snow
17 days 2012-01-18           19.8       0.0      -2.8   5.0    snow
18 days 2012-01-19           15.2      -1.1      -2.8   1.6    snow
19 days 2012-01-20           13.5       7.2      -1.1   2.3    snow
20 days 2012-01-21            3.0       8.3       3.3   8.2    rain

In [ ]:
days = pd.date_range("2025-07-03","2026-02-09",freq="W")
days = pd.date_range("2025-07-03",periods=10,freq="YS")
print(days)

DatetimeIndex(['2026-01-01', '2027-01-01', '2028-01-01', '2029-01-01',
               '2030-01-01', '2031-01-01', '2032-01-01', '2033-01-01',
               '2034-01-01', '2035-01-01'],
              dtype='datetime64[us]', freq='YS-JAN')

In [ ]:
df = pd.read_csv(r'C:\Users\Lenovo\Desktop\Python_Data _analysis\weather.csv',parse_dates=['date'])
# 重新采样
df.set_index('date',inplace=True)

In [ ]:
df[["temp_max", "temp_min"]].resample("YE").mean()

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616

In [ ]:
df[["temp_max", "temp_min"]].resample("YS").mean()

             temp_max  temp_min
date
2012-01-01  15.276776  7.289617
2013-01-01  16.058904  8.153973
2014-01-01  16.995890  8.662466
2015-01-01  17.427945  8.835616

In [ ]:
# 分组聚合
# df.groupby('分组的字段')['聚合的字段'].聚合函数
import pandas as pd
df = pd.read_csv(r'C:\Users\Lenovo\Desktop\课件\代码\data\employees.csv')
df = df.dropna(subset=['department_id'])
df['department_id'] = df['department_id'].astype('int64')
# 计算不同部分的平均薪资
df.groupby('department_id').groups # 查看分组情况
df.groupby('department_id').get_group(110) # 查看特定分组数据情况
df2 = df.groupby('department_id')[['salary']].mean().round(2)
df2 = df2.reset_index()
df2.sort_values('salary',ascending=False)

    department_id    salary
8              90  19333.33
10            110  10150.00
6              70  10000.00
1              20   9500.00
7              80   8955.88
9             100   8600.00
3              40   6500.00
5              60   5760.00
0              10   4400.00
2              30   4150.00
4              50   3475.56

In [ ]:
# 计算不同部分不同岗位的人的平均薪资
df2 = df.groupby(['department_id','job_id'])[['salary']].mean().round(2)
df2 = df2.reset_index()
df2['salary'] = df2['salary'].round(1)
df2.sort_values('salary',ascending=False)

    department_id      job_id   salary
13             90     AD_PRES  24000.0
14             90       AD_VP  17000.0
1              20      MK_MAN  13000.0
11             80      SA_MAN  12200.0
16            100      FI_MGR  12000.0
18            110      AC_MGR  12000.0
4              30      PU_MAN  11000.0
10             70      PR_REP  10000.0
12             80      SA_REP   8396.6
17            110  AC_ACCOUNT   8300.0
15            100  FI_ACCOUNT   7920.0
8              50      ST_MAN   7280.0
5              40      HR_REP   6500.0
2              20      MK_REP   6000.0
9              60     IT_PROG   5760.0
0              10     AD_ASST   4400.0
6              50    SH_CLERK   3215.0
7              50    ST_CLERK   2785.0
3              30    PU_CLERK   2780.0

In [ ]:
# 企鹅数据分析
# 1.导入必要的库
import pandas as pd
import numpy as np
# 2.导入数据
df = pd.read_csv(r'C:\Users\Lenovo\Desktop\课件\代码\data\penguins.csv')
df.head(5)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [ ]:
# 3.数据清洗
# 缺失值的检查
print(df.isna().sum())
df.dropna(inplace=True)

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [ ]:
# 4.数据特征的构造
df['sex'] = df['sex'].astype('category')
df['bill_ratio'] = df['bill_length_mm'] /df['bill_depth_mm']

In [ ]:
# 5.数据分析
# 数据分箱_body_mass_g
labels = ['low', 'mid', 'high']
df['mass_level'] = pd.cut(df['body_mass_g'],bins =3,labels=labels)
print(df['mass_level'].value_counts())
# 按岛屿、性别分组分析
df.groupby(['sex','island']).agg({
    'body_mass_g':['mean','count'],
})

mass_level
low     150
mid     128
high     55
Name: count, dtype: int64

                  body_mass_g
                         mean count
sex    island
Female Biscoe     4319.375000    80
       Dream      3446.311475    61
       Torgersen  3395.833333    24
Male   Biscoe     5104.518072    83
       Dream      3987.096774    62
       Torgersen  4034.782609    23

In [5]:
# 1.导入库
import pandas as pd
import numpy as np
# 2.导入数据
df = pd.read_csv(r'C:\Users\Lenovo\Desktop\课件\代码\data\sleep.csv')
df.head()
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    str
 2   age                      400 non-null    int64
 3   occupation               400 non-null    str
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    str
 9   blood_pressure           400 non-null    str
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
 12  sleep_disorder           110 non-null    str
dtypes: float64(2), int64(6), str(5)
memory usage: 40.8 KB

,person_id,age,sleep_duration,sleep_quality,physical_activity_level,stress_level,heart_rate,daily_steps
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.00000,400.000000,400.000000
mean,200.500000,39.950000,8.041250,6.125750,64.985000,5.47250,75.990000,11076.510000
std,115.614301,14.038883,2.390787,1.975733,32.297874,2.80873,15.099334,5364.789364
min,1.000000,18.000000,4.100000,1.000000,10.000000,1.00000,50.000000,2067.000000
25%,100.750000,29.000000,5.900000,4.700000,35.000000,3.00000,63.000000,6165.250000
50%,200.500000,40.000000,8.200000,6.100000,65.500000,5.00000,77.000000,11785.500000
75%,300.250000,49.000000,10.125000,7.425000,94.000000,8.00000,90.000000,15878.000000
max,400.000000,90.000000,12.000000,10.000000,120.000000,10.00000,100.000000,19958.000000

In [ ]:
# 3.数据清洗
df.isna().sum()
df.drop(columns='sleep_disorder',inplace=True)

KeyError: "['sleep_disorder'] not found in axis"

In [24]:
# 4.数据转换
df['gender'] = df['gender'].astype('category')
df['occupation'] = df['occupation'].astype('category')
df['bmi_category'] = df['bmi_category'].astype('category')
df[['high','low']] = df['blood_pressure'].str.split('/',expand=True)
# 睡眠质量分箱
labels = ['bad','mid','good']
df['quality_level'] = pd.cut(df['sleep_quality'],bins=3,labels=labels)
age_labels = ['青少年', '中年', '老年']
df['age_level'] = pd.cut(df['age'],bins=3,labels=age_labels)
df.head()

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,high,low,quality_level,age_level
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,124,70,mid,青少年
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,131,86,mid,中年
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,122,70,mid,中年
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,124,72,good,青少年
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,133,78,good,老年

In [25]:
# 5.数据分析与统计
print(df['bmi_category'].value_counts())

bmi_category
Overweight     109
Underweight    102
Obese           98
Normal          91
Name: count, dtype: int64

In [27]:
# 根据不同的bmi分组，睡眠质量
df.groupby(['age_level','bmi_category']).agg({
    'sleep_duration':'mean',
    'sleep_quality':'mean',
    'stress_level':'mean'
})

                        sleep_duration  sleep_quality  stress_level
age_level bmi_category
青少年       Normal              8.100000       6.332000      4.860000
          Obese               8.250000       6.253448      5.534483
          Overweight          8.214286       6.171429      5.317460
          Underweight         7.603279       5.883607      5.426230
中年        Normal              7.422222       6.650000      4.944444
          Obese               7.805556       6.216667      5.888889
          Overweight          8.246154       5.956410      5.974359
          Underweight         8.497500       5.907500      5.750000
老年        Normal              7.420000       4.240000      4.200000
          Obese               7.900000       5.025000      8.000000
          Overweight          8.971429       6.285714      6.714286
          Underweight        10.500000       6.200000      6.000000